### ISSUE TITLE
Compile ndnSIM

### ISSUE THREAD

**Issue by Yoomif** [cawka/ndnSIM-tutorial#1]
Dear all,
I try to compile ndnSIM on ubuntu 16.04  according to " https://ndnsim.net/current/getting-started.html#requirements" and when I use ./waf  it says the following error.

I need your help
 
....
[3126/3246] Compiling build/src/visualizer/visualizer/plugins/ndnsim_faces.pyc
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/lib/python2.7/py_compile.py", line 117, in compile
    raise py_exc
py_compile.PyCompileError:   File "/usr/local/lib/python2.7/dist-packages/visualizer/base.py", line 134
    print("Could not load plugin %r: %s" % (filename, str(ex)), file=sys.stderr)
                                                                    ^
SyntaxError: invalid syntax

[3127/3246] Compiling build/src/visualizer/visualizer/plugins/show_last_packets.pyo
Waf: Leaving directory `/home/kichu/ndnSIM/ns-3/build'
Build failed
 -> task in '' failed with exit status 1 (run with -v to display more information)

**Comment by ghost** [comment]
I had the same error on Debian Buster. I ran the ./waf -configure step with the added flag: 
"--with-python=/usr/bin/python3" 
(forcing python 3 rather than python 2 to be used). This allowed the build to complete successfully. 

Also, if you use python 3 you'll need to install the pip modules using pip3 (you can get it via "sudo apt install python3-pip") instead of plain pip (so python 3 can access these installed modules). 
If you run into a problem with "pip3 install graphviz" like I did, the solution here ("sudo apt install graphviz-dev") worked for me: https://github.com/pygraphviz/pygraphviz/issues/163

Best of luck!
